<?php

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Psr\Log\LoggerInterface;

/**
 * appDevUrlGenerator
 *
 * This class has been auto-generated
 * by the Symfony Routing Component.
 */
class appDevUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    private static $declaredRoutes;

    /**
     * Constructor.
     */
    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
        if (null === self::$declaredRoutes) {
            self::$declaredRoutes = array(
        '_wdt' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:toolbarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_wdt',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_home' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:homeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_bar' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchBarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search_bar',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_info' => array (  0 =>   array (    0 => 'about',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:infoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'about',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler/info',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_phpinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:phpinfoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/phpinfo',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_results' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchResultsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/search/results',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_router' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.router:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/router',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception_css' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:cssAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception.css',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_twig_error_test' => array (  0 =>   array (    0 => 'code',    1 => '_format',  ),  1 =>   array (    '_controller' => 'twig.controller.preview_error:previewErrorPageAction',    '_format' => 'html',  ),  2 =>   array (    'code' => '\\d+',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '.',      2 => '[^/]++',      3 => '_format',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'code',    ),    2 =>     array (      0 => 'text',      1 => '/_error',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bufete_homepage' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DefaultController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'homepage' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\DefaultController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'paises_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PaisesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/paises/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'paises_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PaisesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/paises',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'paises_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PaisesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/paises/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'paises_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PaisesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/paises',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'paises_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PaisesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/paises',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'prestaciones_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PrestacionesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/prestaciones/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'prestaciones_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PrestacionesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/prestaciones',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'prestaciones_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PrestacionesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/prestaciones/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'prestaciones_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PrestacionesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/prestaciones',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'prestaciones_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PrestacionesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/prestaciones',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pretenciones_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PretencionesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/pretenciones/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pretenciones_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PretencionesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/pretenciones',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pretenciones_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PretencionesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/pretenciones/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pretenciones_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PretencionesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/pretenciones',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'pretenciones_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PretencionesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/pretenciones',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tribunales_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TribunalesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/tribunales/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tribunales_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TribunalesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tribunales',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tribunales_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TribunalesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/tribunales/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tribunales_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TribunalesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tribunales',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tribunales_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TribunalesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tribunales',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipoasuntos_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipoasuntosController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/tipoasuntos/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipoasuntos_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipoasuntosController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tipoasuntos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipoasuntos_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipoasuntosController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/tipoasuntos/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipoasuntos_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipoasuntosController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tipoasuntos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipoasuntos_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipoasuntosController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tipoasuntos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipocaso_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipocasoController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/tipocaso/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipocaso_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipocasoController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tipocaso',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipocaso_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipocasoController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/tipocaso/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipocaso_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipocasoController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tipocaso',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'tipocaso_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TipocasoController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/tipocaso',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bufetes_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\BufetesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/bufetes/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bufetes_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\BufetesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/bufetes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bufetes_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\BufetesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/bufetes/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bufetes_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\BufetesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/bufetes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bufetes_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\BufetesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/bufetes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandantes_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandantesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/demandantes/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandantes_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandantesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/demandantes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandantes_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandantesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/demandantes/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandantes_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandantesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/demandantes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandantes_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandantesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/demandantes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'departamentos_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DepartamentosController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/departamentos/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'departamentos_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DepartamentosController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/departamentos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'departamentos_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DepartamentosController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/departamentos/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'departamentos_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DepartamentosController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/departamentos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'departamentos_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DepartamentosController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/departamentos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ciudad_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CiudadController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ciudad/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ciudad_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CiudadController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ciudad',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ciudad_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CiudadController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ciudad/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ciudad_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CiudadController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ciudad',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ciudad_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CiudadController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ciudad',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estadosciviles_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstadoscivilesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/estadosciviles/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estadosciviles_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstadoscivilesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/estadosciviles',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estadosciviles_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstadoscivilesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/estadosciviles/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estadosciviles_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstadoscivilesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/estadosciviles',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estadosciviles_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstadoscivilesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/estadosciviles',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'trabajos_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TrabajosController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/trabajos/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'trabajos_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TrabajosController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/trabajos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'trabajos_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TrabajosController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/trabajos/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'trabajos_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TrabajosController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/trabajos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'trabajos_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\TrabajosController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/trabajos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandados_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandadosController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/demandados/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandados_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandadosController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/demandados',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandados_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandadosController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/demandados/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandados_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandadosController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/demandados',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'demandados_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\DemandadosController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/demandados',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'personas_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PersonasController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/personas/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'personas_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PersonasController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/personas',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'personas_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PersonasController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/personas/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'personas_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PersonasController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/personas',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'personas_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\PersonasController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/personas',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estudiantes_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstudiantesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/estudiantes/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estudiantes_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstudiantesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/estudiantes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estudiantes_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstudiantesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/estudiantes/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estudiantes_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstudiantesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/estudiantes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'estudiantes_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\EstudiantesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/estudiantes',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'casos_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CasosController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/casos/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'casos_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CasosController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/casos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'casos_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CasosController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/casos/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'casos_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CasosController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/casos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'casos_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\CasosController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/casos',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'laborales_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\LaboralesController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/laborales/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'laborales_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\LaboralesController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/laborales',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'laborales_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\LaboralesController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/laborales/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'laborales_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\LaboralesController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/laborales',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'laborales_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'BufeteBundle\\Controller\\LaboralesController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/laborales',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
    );
        }
    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
    }
}
