<?php

namespace Proxies\__CG__\BufeteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Demandantes extends \BufeteBundle\Entity\Demandantes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'nombreDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'edadDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'dpiDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'cedulaDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'direccionDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'residenciaDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'dirtrabajoDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'telefonoDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idEstadocivil', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idTrabajo', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idCiudad'];
        }

        return ['__isInitialized__', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'nombreDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'edadDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'dpiDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'cedulaDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'direccionDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'residenciaDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'dirtrabajoDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'telefonoDemandante', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idEstadocivil', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idTrabajo', '' . "\0" . 'BufeteBundle\\Entity\\Demandantes' . "\0" . 'idCiudad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Demandantes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdDemandante()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDemandante();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDemandante', []);

        return parent::getIdDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreDemandante($nombreDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreDemandante', [$nombreDemandante]);

        return parent::setNombreDemandante($nombreDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDemandante', []);

        return parent::getNombreDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdadDemandante($edadDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdadDemandante', [$edadDemandante]);

        return parent::setEdadDemandante($edadDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdadDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdadDemandante', []);

        return parent::getEdadDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpiDemandante($dpiDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpiDemandante', [$dpiDemandante]);

        return parent::setDpiDemandante($dpiDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpiDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpiDemandante', []);

        return parent::getDpiDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedulaDemandante($cedulaDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedulaDemandante', [$cedulaDemandante]);

        return parent::setCedulaDemandante($cedulaDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedulaDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedulaDemandante', []);

        return parent::getCedulaDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionDemandante($direccionDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionDemandante', [$direccionDemandante]);

        return parent::setDireccionDemandante($direccionDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionDemandante', []);

        return parent::getDireccionDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setResidenciaDemandante($residenciaDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResidenciaDemandante', [$residenciaDemandante]);

        return parent::setResidenciaDemandante($residenciaDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getResidenciaDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResidenciaDemandante', []);

        return parent::getResidenciaDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirtrabajoDemandante($dirtrabajoDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirtrabajoDemandante', [$dirtrabajoDemandante]);

        return parent::setDirtrabajoDemandante($dirtrabajoDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirtrabajoDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirtrabajoDemandante', []);

        return parent::getDirtrabajoDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoDemandante($telefonoDemandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoDemandante', [$telefonoDemandante]);

        return parent::setTelefonoDemandante($telefonoDemandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoDemandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoDemandante', []);

        return parent::getTelefonoDemandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstadocivil(\BufeteBundle\Entity\Estadosciviles $idEstadocivil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstadocivil', [$idEstadocivil]);

        return parent::setIdEstadocivil($idEstadocivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstadocivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstadocivil', []);

        return parent::getIdEstadocivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTrabajo(\BufeteBundle\Entity\Trabajos $idTrabajo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTrabajo', [$idTrabajo]);

        return parent::setIdTrabajo($idTrabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTrabajo', []);

        return parent::getIdTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCiudad(\BufeteBundle\Entity\Ciudad $idCiudad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCiudad', [$idCiudad]);

        return parent::setIdCiudad($idCiudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCiudad', []);

        return parent::getIdCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
