<?php

namespace Proxies\__CG__\BufeteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bufetes extends \BufeteBundle\Entity\Bufetes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'idBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'nombreBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'telefono1Bufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'telefono2', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'emailBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'direccionBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'estadoBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'idCiudad'];
        }

        return ['__isInitialized__', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'idBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'nombreBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'telefono1Bufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'telefono2', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'emailBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'direccionBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'estadoBufete', '' . "\0" . 'BufeteBundle\\Entity\\Bufetes' . "\0" . 'idCiudad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bufetes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBufete()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdBufete();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBufete', []);

        return parent::getIdBufete();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreBufete($nombreBufete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreBufete', [$nombreBufete]);

        return parent::setNombreBufete($nombreBufete);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreBufete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreBufete', []);

        return parent::getNombreBufete();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono1Bufete($telefono1Bufete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono1Bufete', [$telefono1Bufete]);

        return parent::setTelefono1Bufete($telefono1Bufete);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono1Bufete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono1Bufete', []);

        return parent::getTelefono1Bufete();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono2($telefono2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono2', [$telefono2]);

        return parent::setTelefono2($telefono2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono2', []);

        return parent::getTelefono2();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailBufete($emailBufete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailBufete', [$emailBufete]);

        return parent::setEmailBufete($emailBufete);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailBufete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailBufete', []);

        return parent::getEmailBufete();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionBufete($direccionBufete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionBufete', [$direccionBufete]);

        return parent::setDireccionBufete($direccionBufete);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionBufete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionBufete', []);

        return parent::getDireccionBufete();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoBufete($estadoBufete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoBufete', [$estadoBufete]);

        return parent::setEstadoBufete($estadoBufete);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoBufete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoBufete', []);

        return parent::getEstadoBufete();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCiudad(\BufeteBundle\Entity\Ciudad $idCiudad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCiudad', [$idCiudad]);

        return parent::setIdCiudad($idCiudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCiudad', []);

        return parent::getIdCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
